# --- Configuración del Sitio ---
site_name: PRSI II - Programación, Redes y Sistemas Informáticos II
site_author: Javier Perales
site_url: https://javier-perales.github.io/PRSI2/ 
site_description: Apuntes y materiales para la asignatura PRSI II.
use_directory_urls: false
# --- Configuración del Tema (Material for MkDocs) ---
theme:
  name: material
  language: es
  icon:
    logo: material/language-python # O el que prefieras de https://materialdesignicons.com/
  palette:
    # Modo claro
    - scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Modo oscuro
    - scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
  #  - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.annotate

extra_css:
  - stylesheets/extra.css
# --- Navegación del Sitio (Aquí organizarás tus temas) ---
nav:
  # - 'Programación didáctica': 'programacion.md'
  - 'Presentación asignatura': 'index.md'
  - 'P1. Del Dato al Modelo':
    - 'Sprint 1: Datos que hablan': 'M1/m1f1.md'
    - 'Sprint 2: Creación de modelos': 'M1/m1f2.md'
    - 'Sprint 3: El lado oscuro de la IA': 'M1/m1f3.md'
  #- 'P2: Del Modelo a la App': []
  #  - 'Sprint 4: Setup y Fundamentos': 'M2/m2f1.md'
  #  - 'Sprint 5: Streamlit': 'M2/m2f2.md'
  #  - 'Sprint 6: Integración del modelo': 'M2/m2f3.md'
  #  - 'Sprint 7: Personalización': 'M2/m2f4.md'
  #- 'P3: El Cerebro Digital': []
  #- 'P4: Redes y Servicios': []

plugins:
  - search


# --- Extensiones de Markdown ---
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
